site_name: betcode FAQ
site_description: FAQ for betcode open-source packages and sports trading generally

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    primary: green
  highlightjs: true

nav:
  - Getting Started: getting-started.md
  - Using Data: using-data.md
  - Developing Strategies: developing-and-testing-strategies.md
  - Deploying: deploying-strategies.md

extra_css:
  - styles/extra.css

markdown_extensions:
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
